micronaut:
  application:
    name: testMicronaut
datasources:
  default:
    url: jdbc:sqlserver://gradingtoolserver.database.windows.net:1433;database=GradingDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: gradingserveradmin
    password: ThisIsDbP@ssword
#    schema-generate: CREATE_DROP
    dialect: SQL_SERVER
jpa.default.properties.hibernate.hbm2ddl.auto: update


